module.exports = {
  // Uncomment the line below to enable the experimental Just-in-Time ("JIT") mode.
  // https://tailwindcss.com/docs/just-in-time-mode
  mode: 'jit',
  theme: {
    fontFamily: {
      sans: ['Roboto'],
      serif: ['Playfair Display'],
    },
    cursor: {
      auto: 'auto',
      default: 'default',
      pointer: 'pointer',
      text: 'text',
      'not-allowed': 'not-allowed',
      crosshair: 'crosshair',
      'zoom-in': 'zoom-in',
      cursor: ['hover', 'focus'],
    },
    minHeight: {
      0: '0',
      '1/4': '25%',
      '1/2': '50%',
      '3/4': '75%',
      full: '100%',
    },
    borderWidth: {
      DEFAULT: '1px',
      0: '0',
      2: '2px',
      3: '3px',
      4: '4px',
      6: '6px',
      8: '8px',
    },
    divideWidth: {
      DEFAULT: '1px',
      0: '0',
      2: '2px',
      3: '3px',
      4: '4px',
      6: '6px',
      8: '8px',
    },
    borderRadius: {
      none: '0',
      sm: '0.125rem',
      DEFAULT: '0.25rem',
      DEFAULT: '4px',
      md: '0.375rem',
      lg: '0.5rem',
      full: '9999px',
      large: '12px',
    },
  },
  variants: {
    extend: {
      accessibility: ['focus-within', 'focus'],
      animation: ['motion-safe'],
      backgroundColor: [
        'dark',
        'group-hover',
        'focus-within',
        'hover',
        'focus',
        'active',
      ],
      backgroundOpacity: [
        'dark',
        'group-hover',
        'focus-within',
        'hover',
        'focus',
      ],
      borderColor: ['dark', 'group-hover', 'focus-within', 'hover', 'focus'],
      borderOpacity: ['dark', 'group-hover', 'focus-within', 'hover', 'focus'],
      borderRadius: ['hover', 'focus'],
      boxShadow: ['group-hover', 'focus-within', 'hover', 'focus'],
      divideColor: ['dark'],
      divideOpacity: ['dark'],
      divideWidth: ['hover', 'focus'],
      gradientColorStops: ['dark', 'hover', 'focus'],
      maxHeight: ['focus'],
      opacity: ['group-hover', 'focus-within', 'hover', 'focus'],
      outline: ['focus-within', 'focus'],
      padding: ['hover'],
      placeholderColor: ['dark', 'focus'],
      placeholderOpacity: ['dark', 'focus'],
      ringColor: ['dark', 'focus-within', 'focus'],
      ringOffsetColor: ['dark', 'focus-within', 'focus'],
      ringOffsetWidth: ['focus-within', 'focus'],
      ringOpacity: ['dark', 'focus-within', 'focus'],
      ringWidth: ['focus-within', 'focus'],
      rotate: ['hover', 'focus'],
      scale: ['hover', 'focus'],
      skew: ['hover', 'focus'],
      textColor: ['dark', 'group-hover', 'focus-within', 'hover', 'focus'],
      textDecoration: [
        'group-hover',
        'focus-within',
        'hover',
        'focus',
        'focus-visible',
      ],
      textOpacity: ['dark', 'group-hover', 'focus-within', 'hover', 'focus'],
      translate: ['hover', 'focus'],
      zIndex: ['focus-within', 'focus'],
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/line-clamp'),
    require('@tailwindcss/aspect-ratio'),
  ],
  purge: {
    // Filenames to scan for classes
    content: [
      './src/**/*.html',
      './src/**/*.js',
      './src/**/*.jsx',
      './src/**/*.ts',
      './src/**/*.tsx',
      './public/index.html',
    ],
    // Options passed to PurgeCSS
    options: {
      // Whitelist specific selectors by name
      // safelist: [],
    },
  },
};
